# -*- coding: utf-8 -*-
"""AgentwithLangchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbPP3N7EHjMCtv4eh4TsD9J4uNRM7HcE

# User Question
#    ↓
# Planner (LLM decides steps)
#    ↓
# Agent Executor
#    ├── Search Tool
#    ├── Calculator Tool
#    └── (Later) RAG Tool
#    ↓
# Final Answer (with reasoning)

> Add blockquote
"""

!pip uninstall -y langchain langchain-core langchain-community

!pip install -q \
  langchain==0.1.20 \
  langchain-community==0.0.38 \
  langchain-google-genai==1.0.5 \
  duckduckgo-search

import os
os.environ["GOOGLE_API_KEY"] = ""

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0
)

from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

from langchain_core.tools import Tool

def calculator(expr: str) -> str:
    try:
        return str(eval(expr))
    except:
        return "Invalid math expression"

calculator_tool = Tool(
    name="Calculator",
    func=calculator,
    description="Use for math calculations"
)

import requests

def weather(city: str) -> str:
    geo = requests.get(
        f"https://geocoding-api.open-meteo.com/v1/search?name={city}"
    ).json()

    if "results" not in geo:
        return "City not found"

    lat = geo["results"][0]["latitude"]
    lon = geo["results"][0]["longitude"]

    data = requests.get(
        f"https://api.open-meteo.com/v1/forecast"
        f"?latitude={lat}&longitude={lon}&current_weather=true"
    ).json()

    temp = data["current_weather"]["temperature"]
    return f"🌤 Weather in {city}: {temp}°C"

weather_tool = Tool(
    name="Weather",
    func=weather,
    description="Get current weather for a city"
)

calendar = []

def add_event(event: str) -> str:
    calendar.append(event)
    return f"Event added: {event}"

def list_events(_: str) -> str:
    return "\n".join(calendar) if calendar else "No events"

calendar_add = Tool(
    name="AddCalendarEvent",
    func=add_event,
    description="Add calendar event"
)

calendar_list = Tool(
    name="ListCalendarEvents",
    func=list_events,
    description="List calendar events"
)

!pip install -q --upgrade langchain langchain-community langchain-google-genai

from langchain_core.agents import AgentExecutor
from langchain_core.chains import LLMChain
from langchain_core.prompts import PromptTemplate

# Wrap the LLM in a chain
prompt = PromptTemplate(
    input_variables=["input"],
    template="Answer the question or call a tool if necessary: {input}"
)

chain = LLMChain(llm=llm, prompt=prompt)

# Create the agent executor
agent = AgentExecutor(
    llm_chain=chain,
    tools=tools,
    verbose=True
)

# Run queries
print(agent.run("Calculate 12 * 15"))
print(agent.run("What's the weather in Delhi?"))
